rover_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001
  kinematics_solver_attempts: 10

  #trac ik
 # kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
 # kinematics_solver_timeout: 0.01
 # kinematics_solver_search_resolution: 0.005
 # kinematics_solver_attempts: 3
 # solve_type: Distance

