planner_plugins:
  ompl_interface/OMPLPlanner:
    planning_plugin: ompl_interface/OMPLPlanner
    default_planner_config: RRTConnect
    request_adapters: >-
      default_planner_request_adapters/AddTimeParameterization
      default_planner_request_adapters/FixWorkspaceBounds
      default_planner_request_adapters/FixStartStateBounds
      default_planner_request_adapters/FixStartStateCollision
      default_planner_request_adapters/FixStartStatePathConstraints
    start_state_max_bounds_error: 0.1

  pilz_industrial_motion_planner/CommandPlanner:
    planning_plugin: pilz_industrial_motion_planner/CommandPlanner
    default_planner_config: PTP

  chomp_interface/CHOMPPlanner:
    planning_plugin: chomp_interface/CHOMPPlanner

