# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    rover_arm_controller:
      type: position_controllers/JointGroupPositionController
      # type: forward_command_controller/ForwardCommandController
      # type: velocity_controllers/JointGroupVelocityController

    rover_arm_controller_moveit:
      type: joint_trajectory_controller/JointTrajectoryController
      # type:  ur_controllers/ScaledJointTrajectoryController
#       type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster




rover_arm_controller:
  ros__parameters:
    joints:
      - base_joint
      - shoulder_joint
      - elbow_pitch_joint
      - elbow_roll_joint
      - wrist_pitch_joint
      - wrist_roll_joint
    interface_name: position

    command_interfaces:
       - position
       - velocity
    state_interfaces:
       - position
       - velocity
rover_arm_controller_moveit:
  ros__parameters:
        joints:
          - base_joint
          - shoulder_joint
          - elbow_pitch_joint
          - elbow_roll_joint
          - wrist_pitch_joint
          - wrist_roll_joint
        state_interfaces:
          - position
          - velocity
        command_interfaces:
          - position

